// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Reprise.Infrastructure.Persistence;

#nullable disable

namespace Reprise.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(RepriseDbContext))]
    [Migration("20260725114855_ClientActionLedger")]
    partial class ClientActionLedger
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Reprise.Domain.Entities.Episode", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateOnly?>("AirDate")
                        .HasColumnType("date")
                        .HasColumnName("air_date");

                    b.Property<int>("EpisodeNumber")
                        .HasColumnType("integer")
                        .HasColumnName("episode_number");

                    b.Property<bool>("IsSpecial")
                        .HasColumnType("boolean")
                        .HasColumnName("is_special");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<bool>("RuntimeEstimated")
                        .HasColumnType("boolean")
                        .HasColumnName("runtime_estimated");

                    b.Property<int?>("RuntimeSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("runtime_seconds");

                    b.Property<long>("SeasonId")
                        .HasColumnType("bigint")
                        .HasColumnName("season_id");

                    b.Property<int>("SeasonNumber")
                        .HasColumnType("integer")
                        .HasColumnName("season_number");

                    b.Property<long>("SeriesId")
                        .HasColumnType("bigint")
                        .HasColumnName("series_id");

                    b.Property<int?>("TmdbId")
                        .HasColumnType("integer")
                        .HasColumnName("tmdb_id");

                    b.HasKey("Id")
                        .HasName("pk_episodes");

                    b.HasIndex("IsSpecial")
                        .HasDatabaseName("ix_episodes_is_special");

                    b.HasIndex("SeasonId")
                        .HasDatabaseName("ix_episodes_season_id");

                    b.HasIndex("SeriesId", "SeasonNumber", "EpisodeNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_episodes_series_id_season_number_episode_number");

                    b.ToTable("episodes", (string)null);
                });

            modelBuilder.Entity("Reprise.Domain.Entities.ImportRun", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("EventsCreated")
                        .HasColumnType("integer")
                        .HasColumnName("events_created");

                    b.Property<DateTimeOffset?>("FinishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finished_at");

                    b.Property<string>("ReconciliationJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("reconciliation_json");

                    b.Property<int>("RowsRead")
                        .HasColumnType("integer")
                        .HasColumnName("rows_read");

                    b.Property<int>("SeriesCreated")
                        .HasColumnType("integer")
                        .HasColumnName("series_created");

                    b.Property<int>("SeriesTmdbMatched")
                        .HasColumnType("integer")
                        .HasColumnName("series_tmdb_matched");

                    b.Property<int>("SeriesUnmatched")
                        .HasColumnType("integer")
                        .HasColumnName("series_unmatched");

                    b.Property<string>("SourceFileSha256")
                        .HasColumnType("text")
                        .HasColumnName("source_file_sha256");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_import_runs");

                    b.ToTable("import_runs", (string)null);
                });

            modelBuilder.Entity("Reprise.Domain.Entities.ProcessedAction", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("AppliedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("applied_at");

                    b.Property<string>("ClientKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("client_key");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("kind");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_processed_actions");

                    b.HasIndex("UserId", "ClientKey")
                        .IsUnique()
                        .HasDatabaseName("ix_processed_actions_user_id_client_key");

                    b.ToTable("processed_actions", (string)null);
                });

            modelBuilder.Entity("Reprise.Domain.Entities.Season", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int?>("EpisodeCount")
                        .HasColumnType("integer")
                        .HasColumnName("episode_count");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("SeasonNumber")
                        .HasColumnType("integer")
                        .HasColumnName("season_number");

                    b.Property<long>("SeriesId")
                        .HasColumnType("bigint")
                        .HasColumnName("series_id");

                    b.Property<int?>("TmdbId")
                        .HasColumnType("integer")
                        .HasColumnName("tmdb_id");

                    b.HasKey("Id")
                        .HasName("pk_seasons");

                    b.HasIndex("SeriesId", "SeasonNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_seasons_series_id_season_number");

                    b.ToTable("seasons", (string)null);
                });

            modelBuilder.Entity("Reprise.Domain.Entities.Series", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("FallbackRuntimeSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("fallback_runtime_seconds");

                    b.Property<DateOnly?>("FirstAirDate")
                        .HasColumnType("date")
                        .HasColumnName("first_air_date");

                    b.Property<bool>("MetadataEnriched")
                        .HasColumnType("boolean")
                        .HasColumnName("metadata_enriched");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("name");

                    b.Property<string>("OriginalName")
                        .HasColumnType("text")
                        .HasColumnName("original_name");

                    b.Property<string>("Overview")
                        .HasColumnType("text")
                        .HasColumnName("overview");

                    b.Property<string>("PosterPath")
                        .HasColumnType("text")
                        .HasColumnName("poster_path");

                    b.Property<string>("Status")
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<int?>("TmdbId")
                        .HasColumnType("integer")
                        .HasColumnName("tmdb_id");

                    b.Property<int?>("TvdbId")
                        .HasColumnType("integer")
                        .HasColumnName("tvdb_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_series");

                    b.HasIndex("TmdbId")
                        .IsUnique()
                        .HasDatabaseName("ix_series_tmdb_id");

                    b.HasIndex("TvdbId")
                        .IsUnique()
                        .HasDatabaseName("ix_series_tvdb_id");

                    b.ToTable("series", (string)null);
                });

            modelBuilder.Entity("Reprise.Domain.Entities.SeriesMatchOverride", b =>
                {
                    b.Property<int>("TvdbId")
                        .HasColumnType("integer")
                        .HasColumnName("tvdb_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Note")
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<int>("TmdbId")
                        .HasColumnType("integer")
                        .HasColumnName("tmdb_id");

                    b.HasKey("TvdbId")
                        .HasName("pk_series_match_overrides");

                    b.ToTable("series_match_overrides", (string)null);
                });

            modelBuilder.Entity("Reprise.Domain.Entities.TrackedSeries", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("AddedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("added_at");

                    b.Property<DateTimeOffset?>("FollowedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("followed_at");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<long>("SeriesId")
                        .HasColumnType("bigint")
                        .HasColumnName("series_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_tracked_series");

                    b.HasIndex("SeriesId")
                        .HasDatabaseName("ix_tracked_series_series_id");

                    b.HasIndex("UserId", "SeriesId")
                        .IsUnique()
                        .HasDatabaseName("ix_tracked_series_user_id_series_id");

                    b.ToTable("tracked_series", (string)null);
                });

            modelBuilder.Entity("Reprise.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.ToTable("users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DisplayName = "Reprise",
                            Email = "me@reprise.local"
                        });
                });

            modelBuilder.Entity("Reprise.Domain.Entities.WatchEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long>("EpisodeId")
                        .HasColumnType("bigint")
                        .HasColumnName("episode_id");

                    b.Property<bool>("IsBackfill")
                        .HasColumnType("boolean")
                        .HasColumnName("is_backfill");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("source");

                    b.Property<string>("SourceKey")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("source_key");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<DateTimeOffset>("WatchedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("watched_at");

                    b.HasKey("Id")
                        .HasName("pk_watch_events");

                    b.HasIndex("EpisodeId")
                        .HasDatabaseName("ix_watch_events_episode_id");

                    b.HasIndex("IsBackfill", "WatchedAt")
                        .HasDatabaseName("ix_watch_events_is_backfill_watched_at");

                    b.HasIndex("UserId", "EpisodeId")
                        .HasDatabaseName("ix_watch_events_user_id_episode_id");

                    b.HasIndex("UserId", "SourceKey")
                        .IsUnique()
                        .HasDatabaseName("ix_watch_events_user_id_source_key")
                        .HasFilter("source_key IS NOT NULL");

                    b.HasIndex("UserId", "WatchedAt")
                        .HasDatabaseName("ix_watch_events_user_id_watched_at");

                    b.ToTable("watch_events", (string)null);
                });

            modelBuilder.Entity("Reprise.Domain.Entities.Episode", b =>
                {
                    b.HasOne("Reprise.Domain.Entities.Season", "Season")
                        .WithMany("Episodes")
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_episodes_seasons_season_id");

                    b.HasOne("Reprise.Domain.Entities.Series", "Series")
                        .WithMany("Episodes")
                        .HasForeignKey("SeriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_episodes_series_series_id");

                    b.Navigation("Season");

                    b.Navigation("Series");
                });

            modelBuilder.Entity("Reprise.Domain.Entities.Season", b =>
                {
                    b.HasOne("Reprise.Domain.Entities.Series", "Series")
                        .WithMany("Seasons")
                        .HasForeignKey("SeriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_seasons_series_series_id");

                    b.Navigation("Series");
                });

            modelBuilder.Entity("Reprise.Domain.Entities.TrackedSeries", b =>
                {
                    b.HasOne("Reprise.Domain.Entities.Series", "Series")
                        .WithMany()
                        .HasForeignKey("SeriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tracked_series_series_series_id");

                    b.Navigation("Series");
                });

            modelBuilder.Entity("Reprise.Domain.Entities.WatchEvent", b =>
                {
                    b.HasOne("Reprise.Domain.Entities.Episode", "Episode")
                        .WithMany("WatchEvents")
                        .HasForeignKey("EpisodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_watch_events_episodes_episode_id");

                    b.Navigation("Episode");
                });

            modelBuilder.Entity("Reprise.Domain.Entities.Episode", b =>
                {
                    b.Navigation("WatchEvents");
                });

            modelBuilder.Entity("Reprise.Domain.Entities.Season", b =>
                {
                    b.Navigation("Episodes");
                });

            modelBuilder.Entity("Reprise.Domain.Entities.Series", b =>
                {
                    b.Navigation("Episodes");

                    b.Navigation("Seasons");
                });
#pragma warning restore 612, 618
        }
    }
}
